version: '3'

services:

  mariadb:
    container_name: mariadb
    networks:
      - inception
    restart: unless-stopped
    build:
      context: ./requirements/mariadb
    env_file:
        - .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
  
  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local # ici nous stockons le volume en local
    driver_opts:
     type: 'none' 									# aucun type spécifique
     o: 'bind'
     device: '/home/avedrenn/data/wordpress' 		#Ou stocker le dossier sur votre ordinateur en local
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'	# Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
      device: '/home/avedrenn/data/mariadb'			#Ou stocker le dossier sur votre ordinateur en local

networks:
  inception:  # création du réseau    
    driver: bridge

